### PR TITLE
Update MainActivity.kt

### PR DESCRIPTION
**Pull request by SlaydeSequeira**
I have added a retry to keep checking if internet has come back as well as i removed observers ondestroy so even though the audio will play in the background no other part of the activity will me running thus reducing power consumption

### CODE REVIEW

**Comment by TangoBeee** [comment]
Hi @SlaydeSequeira,
I’ve noticed that the snackbar isn’t appearing for me. Could you confirm if you’ve tested it? If not, I’d be happy to help troubleshoot!

**Comment by SlaydeSequeira** [comment]
ok I will remove that snackbar and resubmit a pull request, everything else beside that works

**Comment by TangoBeee** [comment]
Sure, take your time.

**Comment by SlaydeSequeira** [comment]
I added the change on my latest pull request features/new features. Sorry for making so many requests it's my 1st open source project.

**Comment by TangoBeee** [comment]
@SlaydeSequeira No need to apologize—it's great to see you involved in open source. I’ll review the code in your latest PR soon.

**Comment by TangoBeee** [comment]
I'll be closing this PR since you've created a new one.

**Pull request closed without merging**
